version: '3.4'

services: 

    letsencrypt:
        image: linuxserver/letsencrypt:latest
        cap_add:
          - NET_ADMIN
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Belgrade #set time zone
          - URL= #your root domain
          - SUBDOMAINS= #your subdomain (sbc)
          - VALIDATION=http
          - EMAIL= #optional
          - DHLEVEL=2048 #optional
          - ONLY_SUBDOMAINS=true #optional
          - EXTRA_DOMAINS= #optional
          - STAGING=false #optional
        volumes:
          - ./letsencrypt:/config
        restart: unless-stopped
        network_mode: host

    kamailio:
        image: 'zeljkoiphouse/kamailio:latest'
        depends_on: 
            - rtpengine
        volumes:
            - ./kamcfg:/etc/kamailio
            - ./letsencrypt/etc/letsencrypt:/cert
            - ./sipdump:/tmp
        restart: unless-stopped
        environment: 
            NEW_CONFIG: 'true'  #if you would like new config files - setting it to true will overwrite your own config files
            EN_SIPDUMP: 'true' #for debuging - your sip capture files will be in sipdump folder
            ADVERTISE_IP: # public ip you would like to advertize
            ALIAS: # public fqdn of your sbc
            SBC_NAME: # public fqdn of your sbc
            SBC_PORT: # tls port of your sbc
            HOST_IP: # the docker host - needed for proper rtp addresing
            UDP_SIP_PORT: # udp sip listen port for sip to pbx
            PBX_IP: # pbx ip you are connecting to Teams DR
            PBX_PORT: # sip port of the above pbx
            RTP_ENG_IP: # usualy the name of rtpengine container (rtpengine in this case)
            RTP_ENG_PORT: '22222' #hardcoded rtp init port
        network_mode: host


    rtpengine:
        image: 'zeljkoiphouse/rtpengine:latest'
        restart: unless-stopped
        environment: 
            # open these ports as low as possible, as docker has slow performanse in opening a lot of ports
            RTP_MAX: '23500' # start port for rtpengine RTP 
            RTP_MIN: '23000' # end port for rtpengine RTP 
            MEDIA_PUB_IP: # public IP of your rtpengine
            NG_LISTEN: '22222' # port for comunication to Kamailio            
        network_mode: host

### if you are adding additional domains to letsencrypt container, you need to mount the same volume to the other containers (./letsencrypt/etc/letsencrypt:/cert)
#### and you need to create additional symlinks (ln -s) in ./letsencrypt/etc/letsencrypt/live folder corresponding to your sbc fqdn name
